### ISSUE TITLE
new header

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#18]
with new background image, should be more "community friendly", maybe showing people...

**Comment by michaelmessina** [comment]
I agree with that. I'm not feeling the green and really the "Share Something" link is not intuitive. 

I lighter background (white with light gray or green border) could be good. The logo inverted for white backgrounds (also easier to transfer across platforms and media, print). Here's a sample of the logo: http://www.facebook.com/interactivesomerville.

The Share Something button could be green, it needs to pop and I'm not sure about the action phrase but could live with it.

We can to some photos also. I might be able to ask someone for some help, otherwise, [if] I have time, I could give it a go.
